---
# 5주차 첫 번째 강의 CoreJavaScript 실습 예제 요점 설명입니다. 
---

---
# 예제 2-9 설명
---
```
console.log(sum(1, 2)); // 함수 선언문인 sum을 호출, JavaScript는 함수 선언문을 호이스팅하여 코드가 실행되기 전에 함수가 이미 정의되어 있기 때문에 에러가 발생하지 않는다. sum(1, 2)은 함수 선언문으로 정의된 sum 함수를 호출하여 1과 2를 더한 결과를 출력한다.

console.log(multiply(3, 4)); // 함수 표현식으로 정의된 multiply를 호출, 함수 표현식은 변수에 함수를 할당하는 방식이므로, 변수 multiply가 선언되기 이전에 호출하면 에러가 발생한다. 이 부분에 의해서 에러가 발생한다.
function sum(a, b) { ... } // 함수 선언문을 사용하여 sum 함수를 정의한다. 함수 선언문은 코드가 실행되기 전에 먼저 호이스팅되므로, 함수를 정의하기 이전에 호출할 수 있다.
var multiply = function(a, b) { ... }; // 함수 표현식을 사용하여 multiply 함수를 정의한다. 함수 표현식은 변수에 함수를 할당하는 방식으로, 변수 multiply가 선언된 이후에야 호출할 수 있다. 따라서 이 부분에서도 에러가 발생한다.

※ 결과적으로:

코드 실행 중 에러가 발생한다.
```
---
# 예제 2-10 설명
---
```
var sum = function sum(a, b) { ... }; // 함수 표현식을 사용하여 변수 sum에 함수를 할당한다. 이 함수는 변수 선언과 동시에 할당되었으므로 변수 선언부만이 호이스팅되고, 할당부는 원래 자리에 남겨진다.
var multiply; // 변수 multiply를 선언한다. 변수 선언부만이 호이스팅되고, 할당은 이후에 이루어지므로 할당은 호이스팅되지 않는다.
console.log(sum(1, 2)); // 변수 sum에 할당된 함수를 호출한다. 함수 표현식에서 함수명 sum은 변수 sum의 스코프 내에서만 유효하므로 호출이 가능하다.
console.log(multiply(3, 4)); // 변수 multiply가 선언된 후에 함수를 할당하였기 때문에, 호출 시 에러가 발생한다. 이때 변수 multiply에는 아직 함수가 할당되어 있지 않은 상태이다.
multiply = function(a, b) { ... }; // 변수 multiply에 함수를 할당한다. 변수 선언은 이미 호이스팅되어 있으므로, 할당 부분은 원래 자리에 남겨진다.

※ 결과적으로:

코드 실행 중 에러가 발생한다.
```
---
# 예제 2-11 설명
---
```
console.log(sum(3, 4)); // 함수 선언문으로 정의된 sum 함수를 호출, 이때, sum 함수의 정의는 이미 위에서 선언되어 있으므로 에러 없이 7이 출력된다.
var a = sum(1, 2); // 변수 a에 sum 함수를 호출한 결과를 할당한다. 이때, 먼저 선언된 함수 선언문으로 정의된 sum 함수가 호출되어 3이 a에 할당된다.
function sum(x, y) { ... } // 함수 선언문을 사용하여 sum 함수를 재정의한다. 이때, 이미 정의된 sum 함수가 다시 정의되므로 이전에 할당된 함수 정의가 무시되고 새로운 함수 정의가 적용된다.
var c = sum(1, 2); // 변수 c에 sum 함수를 호출한 결과를 할당한다. 이때, 새로 재정의된 sum 함수가 호출되어 1 + 2 = 3이 c에 할당된다.

※ 결과적으로:

출력은

7
3
```
---
# 예제 2-12 설명
---
```
onsole.log(sum(3, 4)); // 먼저 sum 함수를 호출한다. 하지만 여기서 에러가 발생한다. 이는 변수 sum에 아직 함수가 할당되지 않았기 때문에 함수를 호출할 수 없다.
var sum = function(x, y) { ... }; // 함수 표현식을 사용하여 sum 변수에 함수를 할당한다. 이 함수는 두 개의 매개변수를 받아서 더한 값을 반환한다.
var a = sum(1, 2); // 변수 a에 sum 함수를 호출한 결과를 할당한다. 이때, sum 변수에 이미 함수가 할당되어 있으므로 정상적으로 호출된다.
var sum = function(x, y) { ... }; // 다시 한 번 함수 표현식을 사용하여 sum 변수에 함수를 할당한다. 이번에는 두 개의 매개변수를 받아서 더한 값을 문자열 형태로 반환한다.
var c = sum(1, 2); // 변수 c에 sum 함수를 호출한 결과를 할당한다. 이때, 이미 새로운 함수가 sum 변수에 할당되어 있으므로 이 함수가 호출되어 1 + 2 = 3이 반환된다.

※ 결과적으로:

코드 실행 중 첫 번째 줄에서 에러가 발생하며, 이후에는 정상적으로 실행된다.
````
